version: '3.5'
services:

  radius:
    build: ../radius/

    volumes:
      - ../conf/radius/:/etc/raddb/
      - ../data/radius/:/var/run/
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"

  web:
    image: "nginx:mainline-alpine"
    ports:
      - "8080:8080"
    volumes:
      - ../conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/deploy/:/var/www/
      - ../data/web/static/:/var/www/static/
      - ../data/web/data/:/var/www/data/
    links:
      - api

  postgres:
    image: "postgres:10-alpine"
    volumes:
      - ../data/pg:/var/lib/postgresql/data
      - ../core/sql/:/docker-entrypoint-initdb.d/
      - ../collector/collector.sql:/docker-entrypoint-initdb.d/02-collector.sql
    environment:
      POSTGRES_DB: billing

  redis:
    image: "redis:alpine"

  rabbit:
    image: "rabbitmq:3-alpine"
    volumes:
      - ../data/rabbit:/var/lib/rabbitmq

  api:
    build: ../api/
    volumes:
      - ../api/:/code
    links:
      - redis
      - postgres
    ports:
      - "8081:8080"

  collector:
    build: ../collector/
    links:
      - postgres
    ports:
      - "2055:2055/udp"
